name: fused-multi-modal-em
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - h5py
  - ipympl
  - ipywidgets
  - jupyterlab
  - jupyterlab-myst
  - tqdm 
  - scikit-image